language: ruby
dist: xenial
cache: bundler

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env: COVERAGE=Summary,Coveralls
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: 2.6
      os: osx
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
